version: 2.1

jobs:
  tag-release:
    machine: true
    resource_class: dukesofhazards/runner
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:Oyb4O4Nipvf6mS2cCvtUNgVir6Pshbcw1IR+/JnkGw0"
      - run:
          name: Create and push version tag
          command: |
            VERSION="1.4.${CIRCLE_BUILD_NUM}"
            git config user.email "andrewnumber1@gmail.com"
            git config user.name "andrewduke51"
            git tag "$VERSION"
            git push origin "$VERSION"
            echo "Tagged release: $VERSION"

workflows:
  release:
    jobs:
      - tag-release:
          context: deployment-an
          filters:
            branches:
              only: master
